// Auto-extracted from "Nudibranchs and Sea Slugs of Koh Tao" (Mehrotra & Urgell, 2018) index.
// 131 species. "Other" is appended in the picker for anything not in the book.
const SLUG_SPECIES = [
  "Aglaja sp.",
  "Aliculastrum debile",
  "Anteaeolidiella cf. cacaotica",
  "Aplysia kurodai",
  "Aplysia parvula",
  "Armina occulta",
  "Armina scotti",
  "Asteronotus cespitosus",
  "Atagema intecta",
  "Atagema spongiosa",
  "Atys semistriata",
  "Baeolidia cf. rieae",
  "Berthella martensi",
  "Bornella hermanni",
  "Bornella johnsonorum",
  "Bornella stellifera",
  "Bursatella leachii",
  "Cadlinella ornatissima",
  "Caloria indica",
  "Carminodoris bifurcata",
  "Ceratosoma tenue",
  "Cerberilla ambonensis",
  "Cerberilla asamusiensis",
  "Cerberilla incola",
  "Cerberilla sp.",
  "Chromodoris cf. mandapamensis",
  "Chromodoris striatella",
  "Coryphellina exoptata",
  "Coryphellina lotos",
  "Costasiella cf. kuroshimae",
  "Costasiella usagi",
  "Dendrodoris denisoni",
  "Dendrodoris elongata",
  "Dendrodoris fumata",
  "Dendrodoris nigra",
  "Dermatobranchus caeruleomaculatus",
  "Dermatobranchus dendronephthyphagus",
  "Dermatobranchus fortunatus",
  "Dermatobranchus semilunus",
  "Dermatobranchus striatus",
  "Discodoris boholiensis",
  "Discodoris cebuensis",
  "Diversidoris aurantionodulosa",
  "Diversidoris crocea",
  "Dorididae sp.",
  "Doriopsis granulosa",
  "Doriprismatica atromarginata",
  "Doris immonda",
  "Elysia asbecki",
  "Elysia cf. japonica",
  "Elysia marginata",
  "Elysia mercieri",
  "Elysia obtusa",
  "Elysia pusilla",
  "Elysia tomentosa",
  "Favorinus sp.",
  "Glossodoris cincta",
  "Goniobranchus aureopurpureus",
  "Goniobranchus cf. rubrocornutus",
  "Goniobranchus fidelis",
  "Goniobranchus geometricus",
  "Goniobranchus preciosus",
  "Goniobranchus reticulatus",
  "Goniobranchus sinensis",
  "Goniobranchus tumuliferus",
  "Goniobranchus verrieri",
  "Goniodoridella sp.",
  "Gymnodoris alba",
  "Gymnodoris ceylonica",
  "Gymnodoris cf. nigricolor",
  "Gymnodoris impudica",
  "Gymnodoris sp.",
  "Halgerda bacalusia",
  "Hallaxa indecora",
  "Haminoea cymbalum",
  "Hypselodoris infucata",
  "Hypselodoris kanga",
  "Hypselodoris maculosa",
  "Hypselodoris maritima",
  "Hypselodoris sp.",
  "Hypselodoris tryoni",
  "Janolus savinkini",
  "Jorunna funebris",
  "Limenandra confusa",
  "Lomanotus vermiformis",
  "Melibe engeli",
  "Melibe viridis",
  "Mexichromis mariei",
  "Mexichromis multituberculata",
  "Mexichromis trilineata",
  "Phestilla lugubris",
  "Phestilla melanobrachia",
  "Phestilla minor",
  "Phestilla sp.",
  "Phidiana militaris",
  "Philine orca",
  "Philinopsis speciosa",
  "Phyllidia coelestis",
  "Phyllidia elegans",
  "Phyllidia nigra",
  "Phyllidia ocellata",
  "Phyllidia picta",
  "Phyllidia varicosa",
  "Phyllidiella pustulosa",
  "Phyllidiopsis loricata",
  "Phyllodesmium magnum",
  "Plakobranchus cf. ocellatus",
  "Plakobranchus cf. papua",
  "Plakobranchus sp.",
  "Platydoris cf. cinereobranchiata",
  "Pleurobranchus forskalii",
  "Polycera sp.",
  "Rostanga sp.",
  "Samla bicolor",
  "Siphopteron makisig",
  "Stylocheilus longicauda",
  "Stylocheilus striatus",
  "Tambja cf. amakusana",
  "Tambja pulcherrima",
  "Tambja sp.",
  "Thecacera sp.",
  "Thuridilla gracilis",
  "Trapania miltabrancha",
  "Trinchesia sp.",
  "Trinchesiidae sp.",
  "Tritonia sp.",
  "Tubulophilinopsis lineolata",
  "Tubulophilinopsis pilsbryi",
  "Tubulophilinopsis reticulata",
  "Unidentia sp.",
  "Verconia cf. hongkongiensis",
];
